apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: es-client
  namespace: efk-logs
  labels:
    k8s-app: elasticsearch-logging
    version: v1
    role: client
spec:
  replicas: 2
  template:
    metadata:
      labels:
        k8s-app: elasticsearch-logging
        version: v1
        role: client
    spec:
      serviceAccountName: es-client
      containers:
      - name: es-client
        image: onlyerich/elasticsearch:v2.4.1-2
        imagePullPolicy: Always
        resources:
          # need more cpu upon initialization, therefore burstable class
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        ports:
        - containerPort: 9200
          name: db
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - name: es-persistent-storage
          mountPath: /data
        env:
        - name: "NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_MASTER
          value: 'false'
        - name: NODE_DATA
          value: 'false'
      volumes:
      - name: es-persistent-storage
        emptyDir: {}