apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: es-master
  namespace: efk-logs
  labels:
    k8s-app: elasticsearch-logging
    version: v1
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    role: master
    master: 'true'
spec:
  replicas: 3
  template:
    metadata:
      labels:
        k8s-app: elasticsearch-logging
        version: v1
        kubernetes.io/cluster-service: "true"
        role: master
        master: 'true'
    spec:
      serviceAccountName: es-master
      containers:
      - name: es-master
        image: onlyerich/elasticsearch:v2.4.1-2
        imagePullPolicy: Always
        resources:
          # need more cpu upon initialization, therefore burstable class
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        ports:
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - name: es-persistent-storage
          mountPath: /data
        env:
        - name: "NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_MASTER
          value: 'true'
        - name: NODE_DATA
          value: 'false'
      volumes:
      - name: es-persistent-storage
        emptyDir: {}